# This workflow runs CI tests for the main package and Examples package
name: CI

# Trigger the workflow on push to main, any pull request, or manual dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

# Ensure only one workflow per ref is running at a time
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Build & Test (Linux)
    runs-on: 
      - self-hosted
      - linter

    steps:
      - name: Install Swiftly
        run: |
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
          tar zxf swiftly-$(uname -m).tar.gz && \
          ./swiftly init --skip-install --assume-yes --no-modify-profile --quiet-shell-followup && \
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
          hash -r
          echo "SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR}" >>"${GITHUB_ENV}"
          echo "SWIFTLY_BIN_DIR=${SWIFTLY_BIN_DIR}" >>"${GITHUB_ENV}"
          echo "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

      - name: Swift version
        run: |
          swiftly install --use ${{ vars.SWIFT_VERSION }} --assume-yes
          
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set working directory to Examples if testing the examples package
      - name: Set working directory
        run: |
          if [ "${{ matrix.package }}" = "Examples" ]; then
            cd Examples
          fi

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test
