name: Test_Examples_SwiftPM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app
  
jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-10-04-a
      - name: cd Examples
        run: cd Examples/
      - name: Build
        run: |
          export TOOLCHAINS=swift
          swift build
      - name: Run tests
        run: |
          swift test -Xswiftc -Xfrontend -Xswiftc -dump-macro-expansions --enable-code-coverage
